import { readFileSync } from "node:fs";
import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { doc, setDoc, serverTimestamp } from "firebase/firestore";
const env = await initializeTestEnvironment({ projectId: "demo-lugaw", firestore: { rules: readFileSync(new URL("../firestore.rules", import.meta.url), "utf8"), host:"127.0.0.1", port:8080 } });
await env.clearFirestore();
await env.withSecurityRulesDisabled(async c => { const db=c.firestore();
  await setDoc(doc(db,"admins/owner"),{name:"Owner"});
  await setDoc(doc(db,"riders/r1"),{name:"R",phone:"09171234567",status:"approved",online:true});
  await setDoc(doc(db,"settings/store"),{open:false}); });
const as=(u,p="password")=>env.authenticatedContext(u,{firebase:{sign_in_provider:p}}).firestore();
const items=Array.from({length:20},(_,i)=>({id:"L0"+i,name:"x",price:39,qty:1}));
const d=(uid,over={})=>({code:"LD-A",customerUid:uid,sellerUid:uid,sellerName:"Owner",mode:"Dine-in",table:"Table 3",notes:"",payment:"Cash",items:items.slice(0,2),subtotal:78,deliveryFee:0,total:78,status:"preparing",riderUid:null,createdAt:serverTimestamp(),...over});
let pass=0,fail=0; const t=async(n,f)=>{try{await f();pass++;console.log("  ok  ",n)}catch(e){fail++;console.log("  FAIL",n)}};
const o=as("owner");
await t("owner records dine-in (store closed online)", ()=>assertSucceeds(setDoc(doc(o,"orders/d1"),d("owner"))));
await t("owner records 20-line dine-in", ()=>assertSucceeds(setDoc(doc(o,"orders/d2"),d("owner",{items,subtotal:780,total:780}))));
await t("owner dine-in without table works", ()=>assertSucceeds(setDoc(doc(o,"orders/d3"),d("owner",{table:""}))));
await t("dine-in with delivery fee refused", ()=>assertFails(setDoc(doc(o,"orders/d4"),d("owner",{deliveryFee:40,total:118}))));
await t("dine-in with fractional qty refused", ()=>assertFails(setDoc(doc(o,"orders/d5"),d("owner",{items:[{id:"L01",name:"x",price:39,qty:1.5}],subtotal:58,total:58}))));
await t("dine-in under someone else's id refused", ()=>assertFails(setDoc(doc(o,"orders/d6"),d("alice"))));
await t("dine-in credited to another seller refused", ()=>assertFails(setDoc(doc(o,"orders/d6b"),d("owner",{sellerUid:"s1"}))));
await t("dine-in without seller refused", ()=>assertFails(setDoc(doc(o,"orders/d6c"),(({sellerUid,sellerName,...r})=>r)(d("owner")))));
await t("customer can't create dine-in", ()=>assertFails(setDoc(doc(as("alice","anonymous"),"orders/d7"),d("alice"))));
await t("dine-in with enough cash given", ()=>assertSucceeds(setDoc(doc(o,"orders/c1"),d("owner",{cashGiven:100}))));
await t("dine-in with exact cash given", ()=>assertSucceeds(setDoc(doc(o,"orders/c2"),d("owner",{cashGiven:78}))));
await t("dine-in with too little cash refused", ()=>assertFails(setDoc(doc(o,"orders/c3"),d("owner",{cashGiven:50}))));
await t("dine-in with text as cash refused", ()=>assertFails(setDoc(doc(o,"orders/c4"),d("owner",{cashGiven:"500"}))));
await t("rider can't create dine-in", ()=>assertFails(setDoc(doc(as("r1"),"orders/d8"),d("r1"))));
console.log(`\n${pass} passed, ${fail} failed`); await env.cleanup(); process.exit(fail?1:0);
